INSERT INTO books( title, genre, cover, description ) VALUES ( 'Better Than Carrots or Sticks', 'education', 'https://images-na.ssl-images-amazon.com/images/I/516zDAq-HsL.jpg', 'Classroom management is traditionally a matter of encouraging good behavior and discouraging bad by doling out rewards and punishments. But studies show that when educators empower students to address and correct misbehavior among themselves, positive results are longer lasting and more wide reaching. In Better Than Carrots or Sticks, longtime educators and best-selling authors Dominique Smith, Douglas Fisher, and Nancy Frey provide a practical blueprint for creating a cooperative and respectful classroom climate in which students and teachers work through behavioral issues together. After a comprehensive overview of the roots of the restorative practices movement in schools, the authors explain how to
* Establish procedures and expectations for student behavior that encourage the development of positive interpersonal skills;' );

INSERT INTO books( title, genre, cover, description ) VALUES ('An Introduction to General Systems Thinking', 'computers', 'https://images-na.ssl-images-amazon.com/images/I/519wB1bO2%2BL._SX331_BO1,204,203,200_.jpg', 'For more than twenty-five years, An Introduction to General Systems Thinking has been hailed as an innovative introduction to systems theory, with applications in computer science and beyond. Used in university courses and professional seminars all over the world, the text has proven its ability to open minds and sharpen thinking.
Originally published in 1975 and reprinted more than twenty times over a quarter century -- and now available for the first time from Dorset House Publishing -- the text uses clear writing and basic algebraic principles to explore new approaches to projects, products, organizations, and virtually any kind of system.
Scientists, engineers, organization leaders, managers, doctors, students, and thinkers of all disciplines can use this book to dispel the mental fog that clouds problem-solving. As author Gerald M. Weinberg writes in the new preface to the Silver Anniversary Edition, "I haven’t changed my conviction that most people don’t think nearly as well as they could had they been taught some principles of thinking.”
Now an award-winning author of nearly forty books spanning the entire software development life cycle, Weinberg had already acquired extensive experience as a programmer, manager, university professor, and consultant when this book was originally published.
With helpful illustrations, numerous end-of-chapter exercises, and an appendix on a mathematical notation used in problem-solving, An Introduction to General Systems Thinking may be your most powerful tool in working with problems, systems, and solutions.' );

INSERT INTO books( title, genre, cover, description ) VALUES ( 'Thinking in Systems: A Primer', 'computers', 'https://images-na.ssl-images-amazon.com/images/I/51NNRZBJ%2BsL._SX330_BO1,204,203,200_.jpg', 'In the years following her role as the lead author of the international bestseller, Limits to Growth―the first book to show the consequences of unchecked growth on a finite planet― Donella Meadows remained a pioneer of environmental and social analysis until her untimely death in 2001.
Thinking in Systems, is a concise and crucial book offering insight for problem solving on scales ranging from the personal to the global. Edited by the Sustainability Institute’s Diana Wright, this essential primer brings systems thinking out of the realm of computers and equations and into the tangible world, showing readers how to develop the systems-thinking skills that thought leaders across the globe consider critical for 21st-century life.
Some of the biggest problems facing the world―war, hunger, poverty, and environmental degradation―are essentially system failures. They cannot be solved by fixing one piece in isolation from the others, because even seemingly minor details have enormous power to undermine the best efforts of too-narrow thinking.
While readers will learn the conceptual tools and methods of systems thinking, the heart of the book is grander than methodology. Donella Meadows was known as much for nurturing positive outcomes as she was for delving into the science behind global dilemmas. She reminds readers to pay attention to what is important, not just what is quantifiable, to stay humble, and to stay a learner.
In a world growing ever more complicated, crowded, and interdependent, Thinking in Systems helps readers avoid confusion and helplessness, the first step toward finding proactive and effective solutions.' );

INSERT INTO books( title, genre, cover, description ) VALUES ( 'JavaScript: The Good Parts', 'computers', 'https://images-na.ssl-images-amazon.com/images/I/5166ztxOm9L._SX381_BO1,204,203,200_.jpg', 'Most programming languages contain good and bad parts, but JavaScript has more than its share of the bad, having been developed and released in a hurry before it could be refined. This authoritative book scrapes away these bad features to reveal a subset of JavaScript thats more reliable, readable, and maintainable than the language as a whole—a subset you can use to create truly extensible and efficient code.
Considered the JavaScript expert by many people in the development community, author Douglas Crockford identifies the abundance of good ideas that make JavaScript an outstanding object-oriented programming language-ideas such as functions, loose typing, dynamic objects, and an expressive object literal notation. Unfortunately, these good ideas are mixed in with bad and downright awful ideas, like a programming model based on global variables.' );

INSERT INTO books( title, genre, cover, description ) VALUES ( 'Cracking the Coding Interview', 'computer', 'https://images-na.ssl-images-amazon.com/images/I/51F6Lwyq5JL._SX348_BO1,204,203,200_.jpg', 'I am not a recruiter. I am a software engineer. And as such, I know what its like to be asked to whip up brilliant algorithms on the spot and then write flawless code on a whiteboard. Ive been through this as a candidate and as an interviewer.
Cracking the Coding Interview, 6th Edition is here to help you through this process, teaching you what you need to know and enabling you to perform at your very best. Ive coached and interviewed hundreds of software engineers. The result is this book.
Learn how to uncover the hints and hidden details in a question, discover how to break down a problem into manageable chunks, develop techniques to unstick yourself when stuck, learn (or re-learn) core computer science concepts, and practice on 189 interview questions and solutions.' );

INSERT INTO books( title, genre, cover, description ) VALUES ( 'Structure and Interpretation of Computer Programs - 2nd Edition (MIT Electrical Engineering and Computer Science)', 'computers', 'https://images-na.ssl-images-amazon.com/images/I/51H17R%2BbW8L._SX331_BO1,204,203,200_.jpg', 'Structure and Interpretation of Computer Programs has had a dramatic impact on computer science curricula over the past decade. This long-awaited revision contains changes throughout the text. There are new implementations of most of the major programming systems in the book, including the interpreters and compilers, and the authors have incorporated many small changes that reflect their experience teaching the course at MIT since the first edition was published. A new theme has been introduced that emphasizes the central role played by different approaches to dealing with time in computational models: objects with state, concurrent programming, functional programming and lazy evaluation, and nondeterministic programming. There are new example sections on higher-order procedures in graphics and on applications of stream processing in numerical programming, and many new exercises. In addition, all the programs have been reworked to run in any Scheme implementation that adheres to the IEEE standard.' );

INSERT INTO books( title, genre, cover, description ) VALUES ( 'The Pragmatic Programmer: From Journeyman to Master', 'computers', 'https://images-na.ssl-images-amazon.com/images/I/41BKx1AxQWL._SX396_BO1,204,203,200_.jpg', '- Ward Cunningham Straight from the programming trenches, The Pragmatic Programmer cuts through the increasing specialization and technicalities of modern software development to examine the core process--taking a requirement and producing working, maintainable code that delights its users. It covers topics ranging from personal responsibility and career development to architectural techniques for keeping your code flexible and easy to adapt and reuse. Read this book, and youll learn how to *Fight software rot; *Avoid the trap of duplicating knowledge; *Write flexible, dynamic, and adaptable code; *Avoid programming by coincidence; *Bullet-proof your code with contracts, assertions, and exceptions; *Capture real requirements; *Test ruthlessly and effectively; *Delight your users; *Build teams of pragmatic programmers; and *Make your developments more precise with automation. Written as a series of self-contained sections and filled with entertaining anecdotes, thoughtful examples, and interesting analogies, The Pragmatic Programmer illustrates the best practices and major pitfalls of many different aspects of software development. Whether youre a new coder, an experienced programm' );

INSERT INTO books( title, genre, cover, description ) VALUES ( 'Professional JavaScript for Web Developers ', 'computers', 'https://images-na.ssl-images-amazon.com/images/I/518NO3X1X2L._SX394_BO1,204,203,200_.jpg', 'This book is aimed at three groups of readers: Experienced object-oriented programming developers looking to learn JavaScript as it relates to traditional OO languages such as Java and C++; Web application developers attempting to enhance site usability; novice JavaScript developers.
Nicholas C. Zakas worked with the Web for over a decade. He has worked on corporate intranet applications used by some of the largest companies in the world and large-scale consumer websites such as MyYahoo! and the Yahoo! homepage. He regularly gives talks at companies and conferences regarding front-end best practices and new technology.' );

INSERT INTO books( title, genre, cover, description ) VALUES ( 'Discussing Design: Improving Communication and Collaboration through Critique', 'computers', 'https://images-na.ssl-images-amazon.com/images/I/512EhdesW7L._SX331_BO1,204,203,200_.jpg', 'Real critique has become a lost skill among collaborative teams today. Critique is intended to help teams strengthen their designs, products, and services, rather than be used to assert authority or push agendas under the guise of "feedback." In this practical guide, authors Adam Connor and Aaron Irizarry teach you techniques, tools, and a framework for helping members of your design team give and receive critique.
Using firsthand stories and lessons from prominent figures in the design community, this book examines the good, the bad, and the ugly of feedback. You’ll come away with tips, actionable insights, activities, and a cheat sheet for practicing critique as a part of your collaborative process.' );

INSERT INTO books( title, genre, cover, description ) VALUES ( 'Designing Interfaces: Patterns for Effective Interaction Design', 'computers', 'https://pictures.abebooks.com/isbn/9780596008031-us.jpg', 'Designing a good interface isnt easy. Users demand software that is well-behaved, good-looking, and easy to use. Your clients or managers demand originality and a short time to market. Your UI technology -- web applications, desktop software, even mobile devices -- may give you the tools you need, but little guidance on how to use them well.
UI designers over the years have refined the art of interface design, evolving many best practices and reusable ideas. If you learn these, and understand why the best user interfaces work so well, you too can design engaging and usable interfaces with less guesswork and more confidence.
Designing Interfaces captures those best practices as design patterns -- solutions to common design problems, tailored to the situation at hand. Each pattern contains practical advice that you can put to use immediately, plus a variety of examples illustrated in full color. Youll get recommendations, design alternatives, and warnings on when not to use them.
Each chapters introduction describes key design concepts that are often misunderstood, such as affordances, visual hierarchy, navigational distance, and the use of color. These give you a deeper understanding of why the patterns work, and how to apply them with more insight.
A book cant design an interface for you -- no foolproof design process is given here -- but Designing Interfaces does give you concrete ideas that you can mix and recombine as you see fit. Experienced designers can use it as a sourcebook of ideas. Novice designers will find a roadmap to the world of interface and interaction design, with enough guidance to start using these patterns immediately.' );

INSERT INTO books( title, genre, cover, description ) VALUES ( 'Designing Multi-Device Experiences: An Ecosystem Approach to User Experiences across Devices', 'computers', 'https://images-na.ssl-images-amazon.com/images/I/51pzyZG-%2BCL._SX331_BO1,204,203,200_.jpg', 'Welcome to our multi-device world, a world where a user’s experience with one application can span many devices—a smartphone, a tablet, a computer, the TV, and beyond. This practical book demonstrates the variety of ways devices relate to each other, combining to create powerful ensembles that deliver superior, integrated experiences to your users.' );
